### ISSUE TITLE
tracking mini project progress

### ISSUE THREAD

**Issue by adam-saudagar** [shayaan245/deffx#1]
JSON
- [x] write a sample json for imdb data
- [x] load that data in python into a dictionary
- [x] print in a human readable format
- [x] take input from user to create new movie record
- [x] write a function to add that new record to the loaded data
- [x] save the newly created data to the file
- [x] write function to delete record
- [x] [BUG] getting error while adding movie after inputing release date
- [x] [improvement] validation check if adding movie with the same name
- [x] while loop in main fn
- [x] code review for improvement (Adam)
  - [ ] move things from global name space into main function
  - [x] formatted output in one string
    - [x] use multiple line to show the template string as currently the line is too big
    - [x] move the list into a new variable, and use that variable in join (to improve code readability)
  - [x] one function for read and write operations
  - [ ] create different function for read and write instead of doing both in `read_write_json`
  - [x] move inputs into one function, and output only in main
    - [x] delete
    - [x] display
    - [x] add

Tkinter
- [x] add movie and movies list screen
  - [x] Movies list and ratings
  - [x] ADD button 
- [x] movie info should be in different gui screen 
- [x] delete screen
  - [x] All movie info
  - [x] close tab button
  - [x] Delete movie flow 
    - [x] Delete movie button
    - [x]  pop up for deleting movie confirmation (yes or no)
       - [x] click on yes movie delets and click on no movie is not deleted
  - [x] record and share showcase 
  - [x] Movie should be deleted as soon as button is pressed(yes button)
  - [x] sound when movie is deleted
- [x] Add movie screen
  - [x] functionality of adding movies
  - [x] validation for contains all entry fields for adding a movie
    - [x] runtime should not be in seconds ,human readable format
    - [x] exception when date entered is incorrect, should give error in read instead 
    - [x] metascore and ratings are accepting only int values not char
    - [x] same with rating score
    - [x] warning below each input box if any detail is empty
    - [x] #4
    - [x] if not there then movie added pop up
  - [x] sound when movie is deleted
    

REST
- [ ] videos for flask
   - [ ] https://www.youtube.com/watch?v=MwZwr5Tvyxo&list=PL-osiE80TeTs4UjLw5MM6OjgkjFeUxCYH
- [ ] documentations and projects for understanding
   - [ ] https://pythonbasics.org/what-is-flask-python/
- [ ] create webserver using flask
- [ ] fetch the data using GET instead of loading it from file
- [ ] create data using POST instead of saving it in file
- [ ] update data using UPDATE instead of updating it in directly

MongoDB
- [ ] instead of loading data from file use mongo db

**Comment by adam-saudagar** [comment]
white board for the app with the wireframe [here](https://wbd.ms/share/v2/aHR0cHM6Ly93aGl0ZWJvYXJkLm1pY3Jvc29mdC5jb20vYXBpL3YxLjAvd2hpdGVib2FyZHMvcmVkZWVtLzRkMjYyZGNlOTA3MDQ5YWNhZTA2NTg4ZmUyZTJjOWNkX0JCQTcxNzYyLTEyRTAtNDJFMS1CMzI0LTVCMTMxRjQyNEUzRF9lZGY1YzNkZS1hZTBlLTQxOGItODQ2MS01ODBiNzk2NzJlM2Q=)
